import { MetadataRoute } from "next";

const base = "https://www.rockandpour.co.uk";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: base, lastModified: new Date(), changeFrequency: "weekly", priority: 1.0 },
    { url: `${base}/events`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/the-experience`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/our-story`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/pricing`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/faq`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/premium-selection`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/drinks-guide`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/bands`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/bowdon-rooms`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/house-rules`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/first-time-guide`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/group-events`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/corporate-events`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/party-planning`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/date-night`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/date-night-manchester`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/stag-do-ideas`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/hen-party-ideas`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/birthday-celebration-ideas`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/team-building-events`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/girls-night-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/lads-night-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/office-night-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/reunion-night-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/altrincham-nights-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/manchester-nights-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/manchester-live-music-events`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/cheshire-events`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/warrington-nights-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/best-manchester-venues`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/live-music-guide`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/why-live-music-matters`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/vs-nightclub`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/vs-pub-crawl`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/vs-normal-night-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/alternative-to-nightclubs`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/all-inclusive-drinks-events`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/group-night-out-ideas`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/best-live-band-venues-uk`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/indie-rock-night`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/night-out-tips`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/what-to-wear-night-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/how-to-budget-night-out`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/rock-music-fans`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/britpop-lovers`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/90s-nostalgia`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/indie-music-fans`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/music-festivals-alternatives`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/best-beer-venues-uk`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/best-wine-venues-uk`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/best-cocktail-venues-uk`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
  ];
}
